# Generated by Django 3.0.4 on 2020-04-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200407_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=69),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=20),
        ),
    ]
